### PR TITLE
Add scaffolding for tests

### PR DESCRIPTION
**Pull request by jtpio**
Add initial scaffolding for tests.

```bash
jlpm
jlpm run test
```

### CODE REVIEW

**Comment by afshin** [comment]
For now, let's not check in `yarn.lock` files. Maybe we should add it to the `.gitignore`?

**Comment by jtpio** [comment]
Sure, we can do that in a separate PR to remove the existing one.

**Comment by afshin** [comment]
Is the `tslint.json` applying itself to the test files?

**Comment by jtpio** [comment]
Then the double quotes should become single quotes, which doesn't seem to be the case.

**Comment by afshin** [comment]
I think `tslint` is passive, so your editor should be complaining?

`jlpm run prettier` is active and will modify your files, though.

**Comment by jtpio** [comment]
VS Code needs the TSLint extension to start complaining.

Otherwise we make prettier run automatically as a git commit hook?

**Comment by afshin** [comment]
Yeah, it's probably a good idea to add it to commit hook.

I'm running VScode with that plugin, but you're right, it should not be required.

**Comment by jtpio** [comment]
Opened #8 for prettier related discussions.

**Pull request merged**
