### PR TITLE
Wrap constraint arguments in `conda` command in quotation marks.

### PR DESCRIPTION
**Pull request by afshin**
cf. https://github.com/jupyterlab/debugger/issues/384

### CODE REVIEW

**Comment by jtpio** [comment]
Are those quotation marks really needed?

Sometimes shells interpret `>` and `=` differently.

**Comment by afshin** [comment]
As the code is before this PR:
```
conda install -c conda-forge xeus-python>=0.6.7 notebook>=6 ptvsd
```
- [x] `bash` succeeds
- [ ] `zsh` fails

After the PR:
```
conda install -c conda-forge "xeus-python>=0.6.7" "notebook>=6" ptvsd
```

- [x] `bash` succeeds
- [x] `zsh` succeeds

**Comment by afshin** [comment]
I ended up having two files: `=0.6.7 ` and `=6` in my home directory 😆

**Comment by jtpio** [comment]
I'm using zsh and it works without the quotes.

**Comment by afshin** [comment]
Hm. This is what happens to me:

conda

**Comment by jtpio** [comment]
Ah ok, thanks for the screencast.

This seems to be caused by the `>`. We could drop it and keep `notebook=6` instead.

**Comment by afshin** [comment]
Yeah, it is definitely the `>`.

I also realized there were several releases of `xeus-python` since we last updated the readme file. So we could just do `notebook=6 xeus-python=0.6`

**Comment by afshin** [comment]
Oh wait, that's wrong. Because if you already have `xeus-python` version `0.6.1` it would not update.

**Comment by jtpio** [comment]
Sounds good :+1: 

And the azure pipelines scripts could follow the same pinning strategy.

**Comment by jtpio** [comment]
> Oh wait, that's wrong. Because if you already have `xeus-python` version `0.6.1` it would not update.

Ah right. Then yes let's pin it everywhere.

**Pull request merged**
