### PR TITLE
Draft command

### PR DESCRIPTION
**Pull request by KrzysztofSikoraCodete**
Related with https://github.com/jupyterlab/debugger/issues/460

This is a draft pull request.

Flow works, however solution is not complete.
Peek 2020-07-27 16-14

### CODE REVIEW

**Comment by jtpio** [comment]
Thanks @KrzysztofSikoraCodete.

> however solution is not complete

What do you think is missing?

**Comment by KrzysztofSikoraCodete** [comment]
@jtpio isEnabled method has hardcooded flag as "true". In all other commands we use there  threadHasStopped(). Maybe in current command is not important?

**Comment by jtpio** [comment]
Closing as we should now make changes to https://github.com/jupyterlab/jupyterlab, in preparation for https://github.com/jupyterlab/debugger/issues/536

**Comment by jtpio** [comment]
Thanks @KrzysztofSikoraCodete for working on this!

**Pull request closed without merging**
