### PR TITLE
Remove the tracker plugin

### PR DESCRIPTION
**Pull request by jtpio**
Addressed the following comment: https://github.com/jupyterlab/debugger/issues/493#issuecomment-662931028

By removing the `tracker` plugin and moving its logic to the `main` plugin.

### CODE REVIEW

**Comment by afshin** [comment]
Should `IDebuggerSources` be `optional` here? Is there a time when it won't be available?

**Comment by jtpio** [comment]
We could imagine a lab build that disables `@jupyterlab/debugger:sources` for example (to disable the opening of read-only editors in the main area).

Also it's general it looks like it can be more flexible to stick to `optional` by default to avoid hard requirements?

Although for now `IDebuggerSources` is still a `require` for `IDebugger`:

https://github.com/jupyterlab/debugger/blob/9698d6f252ce4a366b7300a57e32cfbe0326b92a/src/index.ts#L258

But could be made `optional` too since its options do so:

https://github.com/jupyterlab/debugger/blob/9698d6f252ce4a366b7300a57e32cfbe0326b92a/src/service.ts#L668

**Comment by afshin** [comment]
Yeah that makes sense.

**Comment by afshin** [comment]
Do you want to make it `optional` for `IDebugger` in this PR? Or should we merge this one?

**Comment by jtpio** [comment]
Yes I'll push that now

**Pull request merged**
