### PR TITLE
Remove close command

### LINKED ISSUE #295: Remove the close command
Should the `close` command be removed, so the sidebar is always created and never closed?

While looking at #290, it started to feel a bit confusing to close the debugger sidebar while debugging. That also means users have to keep a mental model that consist of different states:

- the debugger sidebar is open / closed
- the toggle button is on / off 

Removing the possibility to close the sidebar would simplify things greatly. There is only one way to turn on debugging and that is by switching the button on in a notebook, console or file.

For the users who have installed the extension but don't want to use it anymore, they could disable it from the extension manager and that would remove the sidebar.

### PR DESCRIPTION
**Pull request by KsavinN**
resolve #295

### CODE REVIEW

**Comment by jtpio** [comment]
Should we also remove the create from the palette?

**Comment by jtpio** [comment]
Ah too late.

**Comment by jtpio** [comment]
Because the sidebar is created automatically during the plugin initialization.

**Comment by KsavinN** [comment]
we can remove that in separate commit will look better in the commit history.

**Pull request merged**
