### PR TITLE
Column re-sizable in Table Variable

### PR DESCRIPTION
**Pull request by KsavinN**
resolve this issue #366 #74.

Switch from table selectors to flex-box.

table

### CODE REVIEW

**Comment by jtpio** [comment]
@KsavinN do you have a screencast to see what it looks like?

**Comment by jtpio** [comment]
it looks like we should be able to use the data grid (`@lumino/datagrid`) to implement the variable table viewer.

This would have several benefits such as handling large numbers of variables (some users will have hundreds / thousands of variables for sure), resizing, and having other variables (data frames, numpy arrays) look the same everywhere when inspected.

The API is quite different though. I'll look into this in a separate PR.

**Comment by KsavinN** [comment]
Cool, if you implement that I will close that PR without merge.

**Comment by KsavinN** [comment]
Due to end up with implementing dataGrid #391 I close this PR without merge

**Pull request closed without merging**
