### PR TITLE
Install libgbm1 to fix puppeteer in tests

### PR DESCRIPTION
**Pull request by afshin**
Install `libgbm1` to fix puppeteer.

### CODE REVIEW

**Comment by jtpio** [comment]
Strange, the PR is shown as "Closed", but was merged?

It might be related to today's GitHub incident though.

**Comment by jtpio** [comment]
Thanks for the fix by the way!

**Comment by afshin** [comment]
Yeah a weird thing happened to it. It failed and succeeded to merge 😅

**Comment by jtpio** [comment]
We should now be able to undo this change, as the latest CI runs now pull JupyterLab 2.1.1: https://github.com/jupyterlab/debugger/pull/415/checks?check_run_id=615387049

Which includes the puppeteer fix: https://github.com/jupyterlab/jupyterlab/issues/8244#issuecomment-618872270

**Pull request closed without merging**
