### PR TITLE
Add editors to the main area widget

### LINKED ISSUE #56: Add editors to the debugger main area widget
To be done after https://github.com/jupyterlab/debugger/pull/54 is merged.

Quoting https://github.com/jupyterlab/debugger/pull/48#issue-324688768: 

> The Debugger extends BoxPanel class should have an attribute called editors that is a TabPanel of read-only text editors that allow users to add breakpoints

### PR DESCRIPTION
**Pull request by jtpio**
Fixes #56.

The typical usage would involve calling the `addEditor` method when receiving a message from kernel that we hit a breakpoint in a specific file. `addEditor` will show the content of the file that we stepping into (or a previous cell that was executed and then deleted).

This PR does not cover adding breakpoints to the read-only editors (can be done separately).

### CODE REVIEW

**Comment by jtpio** [comment]
Quick look at the current status (using fake data):

code-editors

Still needs a bit of work on the interfaces, model and so on.

**Comment by jtpio** [comment]
@KsavinN @JohanMabille 

I would like to limit the scope of this PR to just adding read-only editors to the debugger main area widget (current state).

Let me know what you think.

Adding breakpoints and handling messages from the kernel can be done in different PRs.

Also since the `expanded` mode removes the sidebar, we should add a way to make the breakpoints, callstack and variables available from the main widget area. I'm not sure the [current design document](https://github.com/jupyterlab/debugger/blob/master/DESIGN.md) covers this.

**Comment by jtpio** [comment]
> Also since the `expanded` mode removes the sidebar, we should add a way to make the breakpoints, callstack and variables available from the main widget area. I'm not sure the [current design document](https://github.com/jupyterlab/debugger/blob/master/DESIGN.md) covers this.

This is tracked in https://github.com/jupyterlab/debugger/issues/38.

**Comment by KsavinN** [comment]
> @KsavinN @JohanMabille
> 
> I would like to limit the scope of this PR to just adding read-only editors to the debugger main area widget (current state).
> 
> Let me know what you think.
> 
> Adding breakpoints and handling messages from the kernel can be done in different PRs.
> 
> Also since the `expanded` mode removes the sidebar, we should add a way to make the breakpoints, callstack and variables available from the main widget area. I'm not sure the [current design document](https://github.com/jupyterlab/debugger/blob/master/DESIGN.md) covers this.

Agree. We should try to make the smallest PR.

**Comment by jtpio** [comment]
Yes, will be adding the `sidebar` as mentioned in https://github.com/jupyterlab/debugger/issues/38 right after.

**Comment by jtpio** [comment]
:+1: 

Follow-up PR will add the sidebar to the main area widget:

image

**Pull request merged**
